---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-release
run:
  path: bosh-cpi-release/ci/tasks/cleanup.sh
params:
  BOSH_OPENSTACK_IDENTITY_API_VERSION: 2.0
  BOSH_OPENSTACK_DOMAIN_NAME:          Default
  BOSH_OPENSTACK_AUTH_URL:             replace-me
  BOSH_OPENSTACK_USERNAME:             replace-me
  BOSH_OPENSTACK_API_KEY:              replace-me
  BOSH_OPENSTACK_PROJECT:              replace-me
  BOSH_OPENSTACK_CA_CERT:              replace-me
