---
platform: linux
image: docker:///bosh/bats
inputs:
  - name: bosh-cpi-release       # --- location of task script to run
  - name: bosh-init              # --- bosh-init executable to do deploy
  - name: bosh-concourse-ci      # --- repository to get manifest and store deployment state file
  - name: bosh-release           # -\
  - name: bosh-cpi-dev-artifacts # -++ used for deployment manifest referenced by manifest_path
  - name: version-semver         # -//
  - name: stemcell               # -/
run:
  path: bosh-cpi-release/ci/tasks/deploy.sh
params:
  base_os:               replace-me
  bats_private_key_data: replace-me
