---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: stemcell
  - name: bats
  - name: terraform-cpi-deploy
  - name: bosh-director-deployment
outputs:
  - name: terraform-bats
run:
  path: bosh-cpi-src-in/ci/tasks/run-dynamic-networking-bats.sh
params:
  bosh_vcap_password:                        replace-me
  openstack_flavor_with_ephemeral_disk:      replace-me
  openstack_flavor_with_no_ephemeral_disk:   replace-me
  private_key_data:                          replace-me
  stemcell_name:                             replace-me
  availability_zone:                         replace-me
  bats_rspec_tags:                           ""