---
platform: linux
image: docker:///bosh/openstack-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: stemcell
  - name: bosh-concourse-ci
run:
  path: bosh-cpi-release/ci/tasks/run-bats.sh
params:
  base_os:              replace-me
  network_type_to_test: replace-me
