---
- type: replace
  path: /releases/name=bosh
  value:
    name: bosh
    url: file://bosh-release.tgz

- type: replace
  path: /releases/name=bosh-openstack-cpi
  value:
    name: bosh-openstack-cpi
    url: file://bosh-openstack-cpi.tgz

- type: replace
  path: /resource_pools/name=vms
  value:
    name: vms
    network: default
    stemcell:
      url: file://stemcell.tgz
    cloud_properties:
      instance_type: ((openstack_flavor))
      availability_zone: ((availability_zone))
    env:
      bosh:
        mbus:
          cert: ((mbus_bootstrap_ssl))

- type: replace
  path: /instance_groups/name=bosh/properties/hm/resurrector_enabled
  value: false

- type: replace
  path: /instance_groups/name=bosh/properties/openstack/endpoint_type?
  value: publicURL

- type: replace
  path: /cloud_provider/properties/openstack/endpoint_type?
  value: publicURL

- type: replace
  path: /instance_groups/name=bosh/properties/director/debug?/keep_unreachable_vms
  value: true

- type: replace
  path: /instance_groups/name=bosh/properties/director/generate_vm_passwords?
  value: false

- type: remove
  path: /instance_groups/name=bosh/properties/dns/recursor?
