---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: dummy-release
  - name: stemcell
  - name: terraform
  - name: terraform-secondary-openstack
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/deploy-dummy-release-multiple-availability-zones.sh
params:
  bosh_admin_password:         replace-me
  stemcell_name:               replace-me
  instance_flavor:             replace-me
  delete_deployment_when_done: replace-me
  api_key_left:                replace-me
  auth_url_left:               replace-me
  project_left:                replace-me
  domain_left:                 replace-me
  username_left:               replace-me
  api_key_right:               replace-me
  auth_url_right:              replace-me
  project_right:               replace-me
  domain_right:                replace-me
  username_right:              replace-me
  root_ca_pem:                 replace-me
  root_ca_key:                 replace-me