---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: old-bosh-init
outputs:
  - name: deployment
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/deploy-old-director.sh
params:
  BOSH_INIT_LOG_LEVEL:                 warn
  bosh_admin_password:                 replace-me
  dns:                                 replace-me
  v3_e2e_flavor:                       replace-me
  v3_e2e_connection_timeout:           replace-me
  v3_e2e_read_timeout:                 replace-me
  v3_e2e_state_timeout:                replace-me
  v3_e2e_write_timeout:                replace-me
  bosh_openstack_ca_cert:              replace-me
  v3_e2e_bosh_registry_port:           replace-me
  v3_e2e_api_key:                      replace-me
  v3_e2e_auth_url:                     replace-me
  v3_e2e_default_key_name:             replace-me
  v3_upgrade_director_floating_ip:     replace-me
  v3_upgrade_director_manual_ip:       replace-me
  v3_e2e_net_cidr:                     replace-me
  v3_e2e_net_gateway:                  replace-me
  v3_e2e_net_id:                       replace-me
  v3_e2e_security_group:               replace-me
  v3_e2e_project:                      replace-me
  v3_e2e_domain:                       replace-me
  v3_e2e_username:                     replace-me
  v3_e2e_private_key_data:             replace-me
  old_bosh_release_version:            replace-me
  old_bosh_release_sha1:               replace-me
  old_openstack_cpi_release_version:   replace-me
  old_openstack_cpi_release_sha1:      replace-me
  old_bosh_stemcell_name:              replace-me
  old_bosh_stemcell_version:           replace-me
  old_bosh_stemcell_sha1:              replace-me
  time_server_1:                       replace-me
  time_server_2:                       replace-me
  s3_compiled_bosh_release_access_key: replace-me
  s3_compiled_bosh_release_secret_key: replace-me
  distro:                              replace-me
