---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: bosh-cpi-dev-artifacts
  - name: bosh-init
  - name: bosh-release
  - name: stemcell
  - name: deployment
outputs:
  - name: upgrade-deployment
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/test-upgrade.sh
params:
  BOSH_INIT_LOG_LEVEL:               warn
  dns:                               replace-me
  v3_e2e_flavor:                     replace-me
  v3_e2e_connection_timeout:         replace-me
  v3_e2e_read_timeout:               replace-me
  v3_e2e_state_timeout:              replace-me
  v3_e2e_write_timeout:              replace-me
  bosh_openstack_ca_cert:            replace-me
  v3_e2e_bosh_registry_port:         replace-me
  v3_e2e_api_key:                    replace-me
  v3_e2e_auth_url:                   replace-me
  v3_e2e_default_key_name:           replace-me
  v3_upgrade_director_floating_ip:   replace-me
  v3_upgrade_director_manual_ip:     replace-me
  v3_e2e_net_cidr:                   replace-me
  v3_e2e_net_gateway:                replace-me
  v3_e2e_net_id:                     replace-me
  v3_e2e_security_group:             replace-me
  v3_e2e_project:                    replace-me
  v3_e2e_domain:                     replace-me
  v3_e2e_username:                   replace-me
  v3_e2e_private_key_data:           replace-me
