---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: bosh-cpi-release
  - name: bosh-release
  - name: stemcell
  - name: director-deployment
  - name: dummy-deployment
  - name: terraform
outputs:
  - name: upgrade-deployment
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/test-upgrade.sh
params:
  BOSH_INIT_LOG_LEVEL:                 warn
  bosh_admin_password:                 ""
  v3_e2e_flavor:                       ""
  v3_e2e_connection_timeout:           ""
  v3_e2e_read_timeout:                 ""
  v3_e2e_state_timeout:                ""
  v3_e2e_write_timeout:                ""
  v3_e2e_bosh_registry_port:           ""
  v3_e2e_api_key:                      ""
  v3_e2e_auth_url:                     ""
  v3_e2e_project:                      ""
  v3_e2e_domain:                       ""
  v3_e2e_username:                     ""
  v3_e2e_private_key_data:             ""
  time_server_1:                       ""
  time_server_2:                       ""
  distro:                              ""
  bosh_openstack_ca_cert:              replace-me