---
ruby_openstack_cpi/yaml-0.1.5.tar.gz:
  object_id: 6ea9080c-2ec1-4f5c-98d1-d3d5db8f1bf8
  sha: 8b78cb9f759c7d80db8a7328c0ebecfe34fde737
  size: 504897
ruby_openstack_cpi/bundler-1.6.3.gem:
  object_id: 4f5b215e-5926-4a1f-813c-917b820cab65
  sha: c8a000f75b6a6f60d9fb727f8076ec9171e14c20
  size: 293376
ruby_openstack_cpi/ruby-2.1.4.tar.gz:
  object_id: 8a09e95e-c2f9-4e5f-9e65-f69d76027bd4
  sha: 29e9cfdd9e989b7621d7696ef3f970262a08dbc3
  size: 15127418
ruby_openstack_cpi/rubygems-2.3.0.tgz:
  object_id: 07b2b432-298c-4783-85f3-a1d028b42bfb
  sha: 6902fff7749fa264b8f9020f33daf92170375f75
  size: 431240
ruby_openstack_cpi/little-plugger-1.1.3.gem:
  object_id: 64bff80e-a99e-490a-ae10-aa782667e367
  sha: 0ee5988d07bb701efbada9a9c51017b3b7a3af49
  size: 9216
