---
ruby_openstack_cpi/ruby-1.9.3-p545.tar.gz:
  object_id: 3365e9d2-b873-44ad-9d8a-8dd7e216408d
  sha: 03455364740914e8d2dfd6421f681b3fb68a4313
  size: 12582277
ruby_openstack_cpi/rubygems-2.1.11.tgz:
  object_id: d709e5e9-07bc-44ff-b7b5-747baa1a884c
  sha: ca3033432cae28deb7ced79cda271cb292b70e59
  size: 367166
ruby_openstack_cpi/yaml-0.1.5.tar.gz:
  object_id: 6ea9080c-2ec1-4f5c-98d1-d3d5db8f1bf8
  sha: 8b78cb9f759c7d80db8a7328c0ebecfe34fde737
  size: 504897
ruby_openstack_cpi/bundler-1.8.2.gem:
  object_id: b1679c6f-12a6-4f30-8190-a32615573b36
  sha: e9b810268eea94ac5e825b5ae8a2d5fd19fb5905
  size: 235008
ruby_openstack_cpi/ruby-2.1.7.tar.gz:
  object_id: f1564a13-9316-4564-af5b-fc13d3f0793f
  sha: e2e195a4a58133e3ad33b955c829bb536fa3c075
  size: 15151458
